export { ScoreDisplay } from './score-display.web'
export { LetterCard } from './letter-card.web'
export { TypingInput } from './typing-input.web'
export { CheckButton } from './check-button.web'
export { InstructionsBox } from './instructions-box.web'
export { PaginationControls } from './pagination-controls.web'
export { AlphabetTypingLayout } from './layout/alphabet-typing-layout.web'
export { AlphabetTypingMain } from './layout/alphabet-typing-main.web'
export { AlphabetTypingLayout as AlphabetTypingLayoutMobile } from './layout/alphabet-typing-layout.mobile'
export { AlphabetTypingMain as AlphabetTypingMainMobile } from './layout/alphabet-typing-main.mobile'

