// Mock data cho Admin Panel - ít nhất 20 items mỗi loại

export const mockUsers = [
  { id: 'u1', name: 'Alice Admin', email: 'alice@tokki.io', role: 'Admin', status: 'Active' },
  { id: 'u2', name: 'Bob Staff', email: 'bob@tokki.io', role: 'Staff', status: 'Active' },
  { id: 'u3', name: 'Carol User', email: 'carol@tokki.io', role: 'User', status: 'Suspended' },
  { id: 'u4', name: 'David Nguyen', email: 'david.nguyen@tokki.io', role: 'Admin', status: 'Active' },
  { id: 'u5', name: 'Emma Tran', email: 'emma.tran@tokki.io', role: 'Staff', status: 'Active' },
  { id: 'u6', name: 'Frank Lee', email: 'frank.lee@tokki.io', role: 'User', status: 'Active' },
  { id: 'u7', name: 'Grace Kim', email: 'grace.kim@tokki.io', role: 'User', status: 'Active' },
  { id: 'u8', name: 'Henry Park', email: 'henry.park@tokki.io', role: 'Staff', status: 'Active' },
  { id: 'u9', name: 'Ivy Chen', email: 'ivy.chen@tokki.io', role: 'User', status: 'Suspended' },
  { id: 'u10', name: 'Jack Wang', email: 'jack.wang@tokki.io', role: 'User', status: 'Active' },
  { id: 'u11', name: 'Kelly Zhang', email: 'kelly.zhang@tokki.io', role: 'Staff', status: 'Active' },
  { id: 'u12', name: 'Liam Brown', email: 'liam.brown@tokki.io', role: 'User', status: 'Active' },
  { id: 'u13', name: 'Mia Johnson', email: 'mia.johnson@tokki.io', role: 'Admin', status: 'Active' },
  { id: 'u14', name: 'Noah Davis', email: 'noah.davis@tokki.io', role: 'User', status: 'Suspended' },
  { id: 'u15', name: 'Olivia Wilson', email: 'olivia.wilson@tokki.io', role: 'Staff', status: 'Active' },
  { id: 'u16', name: 'Paul Martinez', email: 'paul.martinez@tokki.io', role: 'User', status: 'Active' },
  { id: 'u17', name: 'Quinn Anderson', email: 'quinn.anderson@tokki.io', role: 'User', status: 'Active' },
  { id: 'u18', name: 'Rachel Taylor', email: 'rachel.taylor@tokki.io', role: 'Staff', status: 'Active' },
  { id: 'u19', name: 'Sam Thomas', email: 'sam.thomas@tokki.io', role: 'Admin', status: 'Active' },
  { id: 'u20', name: 'Tina Jackson', email: 'tina.jackson@tokki.io', role: 'User', status: 'Suspended' },
  { id: 'u21', name: 'Uma White', email: 'uma.white@tokki.io', role: 'User', status: 'Active' },
  { id: 'u22', name: 'Victor Harris', email: 'victor.harris@tokki.io', role: 'Staff', status: 'Active' },
]

export const mockLessons = [
  { id: 'l1', title: 'Lesson 1: Greetings', author: 'Team Tokki', updatedAt: '2024-01-15' },
  { id: 'l2', title: 'Lesson 2: Numbers', author: 'Team Tokki', updatedAt: '2024-01-20' },
  { id: 'l3', title: 'Lesson 3: Family Members', author: 'Nguyen Van A', updatedAt: '2024-01-25' },
  { id: 'l4', title: 'Lesson 4: Daily Activities', author: 'Tran Thi B', updatedAt: '2024-02-01' },
  { id: 'l5', title: 'Lesson 5: Food and Drinks', author: 'Team Tokki', updatedAt: '2024-02-05' },
  { id: 'l6', title: 'Lesson 6: Colors', author: 'Le Van C', updatedAt: '2024-02-10' },
  { id: 'l7', title: 'Lesson 7: Weather', author: 'Pham Thi D', updatedAt: '2024-02-15' },
  { id: 'l8', title: 'Lesson 8: Transportation', author: 'Team Tokki', updatedAt: '2024-02-20' },
  { id: 'l9', title: 'Lesson 9: Shopping', author: 'Hoang Van E', updatedAt: '2024-02-25' },
  { id: 'l10', title: 'Lesson 10: Hobbies', author: 'Team Tokki', updatedAt: '2024-03-01' },
  { id: 'l11', title: 'Lesson 11: Time and Dates', author: 'Vu Thi F', updatedAt: '2024-03-05' },
  { id: 'l12', title: 'Lesson 12: Directions', author: 'Team Tokki', updatedAt: '2024-03-10' },
  { id: 'l13', title: 'Lesson 13: Health and Body', author: 'Dang Van G', updatedAt: '2024-03-15' },
  { id: 'l14', title: 'Lesson 14: Emotions', author: 'Bui Thi H', updatedAt: '2024-03-20' },
  { id: 'l15', title: 'Lesson 15: Jobs and Careers', author: 'Team Tokki', updatedAt: '2024-03-25' },
  { id: 'l16', title: 'Lesson 16: Travel', author: 'Do Van I', updatedAt: '2024-04-01' },
  { id: 'l17', title: 'Lesson 17: Technology', author: 'Team Tokki', updatedAt: '2024-04-05' },
  { id: 'l18', title: 'Lesson 18: Education', author: 'Ngo Thi K', updatedAt: '2024-04-10' },
  { id: 'l19', title: 'Lesson 19: Sports and Fitness', author: 'Team Tokki', updatedAt: '2024-04-15' },
  { id: 'l20', title: 'Lesson 20: Entertainment', author: 'Ly Van L', updatedAt: '2024-04-20' },
  { id: 'l21', title: 'Lesson 21: Nature and Environment', author: 'Team Tokki', updatedAt: '2024-04-25' },
  { id: 'l22', title: 'Lesson 22: Festivals and Holidays', author: 'Truong Thi M', updatedAt: '2024-05-01' },
]

export const mockArticles = [
  { id: 'a1', title: 'Học tiếng Anh hiệu quả', author: 'Content Team', published: true },
  { id: 'a2', title: 'Mẹo phát âm chuẩn', author: 'Linguist', published: false },
  { id: 'a3', title: '10 cách học từ vựng nhanh nhất', author: 'Education Expert', published: true },
  { id: 'a4', title: 'Ngữ pháp tiếng Anh cơ bản', author: 'Grammar Master', published: true },
  { id: 'a5', title: 'Luyện nghe tiếng Anh hàng ngày', author: 'Content Team', published: true },
  { id: 'a6', title: 'Cách viết email chuyên nghiệp', author: 'Business Writer', published: false },
  { id: 'a7', title: 'Từ vựng chủ đề công việc', author: 'Career Coach', published: true },
  { id: 'a8', title: 'Học tiếng Anh qua phim ảnh', author: 'Entertainment Guide', published: true },
  { id: 'a9', title: 'Ngữ pháp nâng cao: Conditional', author: 'Grammar Master', published: false },
  { id: 'a10', title: 'Tips cho kỳ thi IELTS', author: 'IELTS Expert', published: true },
  { id: 'a11', title: 'Từ vựng du lịch', author: 'Travel Blogger', published: true },
  { id: 'a12', title: 'Cách đọc hiểu nhanh', author: 'Reading Specialist', published: true },
  { id: 'a13', title: 'Thành ngữ tiếng Anh thông dụng', author: 'Idiom Expert', published: false },
  { id: 'a14', title: 'Luyện nói tiếng Anh tự tin', author: 'Speaking Coach', published: true },
  { id: 'a15', title: 'Từ vựng chủ đề công nghệ', author: 'Tech Writer', published: true },
  { id: 'a16', title: 'Ngữ pháp: Passive Voice', author: 'Grammar Master', published: true },
  { id: 'a17', title: 'Học tiếng Anh qua bài hát', author: 'Music Lover', published: false },
  { id: 'a18', title: 'Từ vựng y tế cơ bản', author: 'Medical Translator', published: true },
  { id: 'a19', title: 'Cách viết CV bằng tiếng Anh', author: 'Career Coach', published: true },
  { id: 'a20', title: 'Lỗi ngữ pháp thường gặp', author: 'Grammar Master', published: true },
  { id: 'a21', title: 'Từ vựng chủ đề giáo dục', author: 'Education Expert', published: false },
  { id: 'a22', title: 'Học tiếng Anh cho người mới bắt đầu', author: 'Content Team', published: true },
]

export const mockSystemLogs = [
  { id: 'log1', level: 'info', message: 'User login success', timestamp: '2024-05-20 10:00:00' },
  { id: 'log2', level: 'warn', message: 'High memory usage detected', timestamp: '2024-05-20 10:15:23' },
  { id: 'log3', level: 'info', message: 'New user registered', timestamp: '2024-05-20 11:30:45' },
  { id: 'log4', level: 'error', message: 'Database connection timeout', timestamp: '2024-05-20 12:00:12' },
  { id: 'log5', level: 'info', message: 'Lesson created successfully', timestamp: '2024-05-20 13:20:33' },
  { id: 'log6', level: 'warn', message: 'API rate limit approaching', timestamp: '2024-05-20 14:05:56' },
  { id: 'log7', level: 'info', message: 'Vocabulary updated', timestamp: '2024-05-20 15:10:22' },
  { id: 'log8', level: 'info', message: 'Article published', timestamp: '2024-05-20 16:25:44' },
  { id: 'log9', level: 'error', message: 'Failed to send email notification', timestamp: '2024-05-20 17:40:15' },
  { id: 'log10', level: 'info', message: 'User profile updated', timestamp: '2024-05-20 18:00:30' },
  { id: 'log11', level: 'warn', message: 'Disk space low', timestamp: '2024-05-20 19:15:48' },
  { id: 'log12', level: 'info', message: 'Backup completed successfully', timestamp: '2024-05-20 20:30:12' },
  { id: 'log13', level: 'info', message: 'System maintenance started', timestamp: '2024-05-20 21:45:25' },
  { id: 'log14', level: 'error', message: 'Payment gateway error', timestamp: '2024-05-20 22:10:40' },
  { id: 'log15', level: 'info', message: 'Cache cleared', timestamp: '2024-05-20 23:20:55' },
  { id: 'log16', level: 'warn', message: 'Unusual activity detected', timestamp: '2024-05-21 08:00:10' },
  { id: 'log17', level: 'info', message: 'New lesson published', timestamp: '2024-05-21 09:15:33' },
  { id: 'log18', level: 'info', message: 'User subscription renewed', timestamp: '2024-05-21 10:30:45' },
  { id: 'log19', level: 'error', message: 'File upload failed', timestamp: '2024-05-21 11:45:20' },
  { id: 'log20', level: 'info', message: 'Password reset requested', timestamp: '2024-05-21 12:00:35' },
  { id: 'log21', level: 'warn', message: 'Session expired', timestamp: '2024-05-21 13:15:50' },
  { id: 'log22', level: 'info', message: 'Export data completed', timestamp: '2024-05-21 14:30:12' },
]

// Mock data cho các gói thành viên
export const mockMembershipPackages = [
  {
    id: 'p1',
    name: 'VIP MONTHLY',
    duration: '1 tháng',
    durationMonths: 1,
    price: 99000,
    description: 'Gói thành viên VIP hàng tháng với đầy đủ tính năng',
    features: ['Truy cập không giới hạn', 'Học offline', 'Hỗ trợ 24/7'],
    status: 'active',
  },
  {
    id: 'p2',
    name: 'VIP SEMI-ANNUAL',
    duration: '6 tháng',
    durationMonths: 6,
    price: 499000,
    description: 'Gói thành viên VIP 6 tháng - Tiết kiệm 16%',
    features: ['Truy cập không giới hạn', 'Học offline', 'Hỗ trợ 24/7', 'Ưu đãi đặc biệt'],
    status: 'active',
  },
  {
    id: 'p3',
    name: 'VIP ANNUAL',
    duration: '1 năm',
    durationMonths: 12,
    price: 899000,
    description: 'Gói thành viên VIP 1 năm - Tiết kiệm 24%',
    features: ['Truy cập không giới hạn', 'Học offline', 'Hỗ trợ 24/7', 'Ưu đãi đặc biệt', 'Quà tặng độc quyền'],
    status: 'active',
  },
]

// Mock data cho feedback
export const mockFeedbacks = [
  {
    id: 'fb1',
    userId: 'u1',
    userName: 'Alice Admin',
    userEmail: 'alice@tokki.io',
    subject: 'Góp ý về giao diện',
    content: 'Giao diện rất đẹp nhưng tôi muốn có thêm tính năng dark mode.',
    status: 'new',
    createdAt: '2024-05-21 10:30:00',
    category: 'ui',
  },
  {
    id: 'fb2',
    userId: 'u6',
    userName: 'Frank Lee',
    userEmail: 'frank.lee@tokki.io',
    subject: 'Lỗi khi học bài',
    content: 'Tôi gặp lỗi khi làm bài tập, hệ thống không lưu được kết quả.',
    status: 'in-progress',
    createdAt: '2024-05-21 09:15:00',
    category: 'bug',
  },
  {
    id: 'fb3',
    userId: 'u7',
    userName: 'Grace Kim',
    userEmail: 'grace.kim@tokki.io',
    subject: 'Đề xuất tính năng mới',
    content: 'Có thể thêm tính năng học offline không? Tôi muốn học khi không có internet.',
    status: 'resolved',
    createdAt: '2024-05-20 14:20:00',
    category: 'feature',
  },
  {
    id: 'fb4',
    userId: 'u10',
    userName: 'Jack Wang',
    userEmail: 'jack.wang@tokki.io',
    subject: 'Cảm ơn đội ngũ',
    content: 'Cảm ơn đội ngũ đã tạo ra ứng dụng tuyệt vời này!',
    status: 'new',
    createdAt: '2024-05-20 11:45:00',
    category: 'other',
  },
  {
    id: 'fb5',
    userId: 'u12',
    userName: 'Liam Brown',
    userEmail: 'liam.brown@tokki.io',
    subject: 'Vấn đề về tốc độ tải',
    content: 'Ứng dụng tải chậm khi có nhiều người dùng cùng lúc.',
    status: 'in-progress',
    createdAt: '2024-05-19 16:30:00',
    category: 'bug',
  },
  {
    id: 'fb6',
    userId: 'u15',
    userName: 'Olivia Wilson',
    userEmail: 'olivia.wilson@tokki.io',
    subject: 'Đề xuất thêm ngôn ngữ',
    content: 'Có thể thêm hỗ trợ tiếng Nhật và tiếng Hàn không?',
    status: 'new',
    createdAt: '2024-05-19 10:20:00',
    category: 'feature',
  },
  {
    id: 'fb7',
    userId: 'u8',
    userName: 'Henry Park',
    userEmail: 'henry.park@tokki.io',
    subject: 'Lỗi đăng nhập',
    content: 'Tôi không thể đăng nhập bằng tài khoản Google.',
    status: 'resolved',
    createdAt: '2024-05-18 14:15:00',
    category: 'bug',
  },
  {
    id: 'fb8',
    userId: 'u11',
    userName: 'Kelly Zhang',
    userEmail: 'kelly.zhang@tokki.io',
    subject: 'Giao diện mobile cần cải thiện',
    content: 'Giao diện trên mobile chưa thân thiện, cần tối ưu hơn.',
    status: 'new',
    createdAt: '2024-05-18 09:30:00',
    category: 'ui',
  },
  {
    id: 'fb9',
    userId: 'u16',
    userName: 'Paul Martinez',
    userEmail: 'paul.martinez@tokki.io',
    subject: 'Tính năng lưu tiến độ',
    content: 'Rất hữu ích khi có tính năng lưu tiến độ học tập.',
    status: 'resolved',
    createdAt: '2024-05-17 15:45:00',
    category: 'feature',
  },
  {
    id: 'fb10',
    userId: 'u18',
    userName: 'Rachel Taylor',
    userEmail: 'rachel.taylor@tokki.io',
    subject: 'Lỗi phát âm',
    content: 'Phần phát âm không hoạt động đúng với một số từ.',
    status: 'in-progress',
    createdAt: '2024-05-17 11:20:00',
    category: 'bug',
  },
  {
    id: 'fb11',
    userId: 'u21',
    userName: 'Uma White',
    userEmail: 'uma.white@tokki.io',
    subject: 'Đề xuất thêm bài tập',
    content: 'Cần thêm nhiều bài tập thực hành hơn cho mỗi bài học.',
    status: 'new',
    createdAt: '2024-05-16 13:10:00',
    category: 'feature',
  },
  {
    id: 'fb12',
    userId: 'u22',
    userName: 'Victor Harris',
    userEmail: 'victor.harris@tokki.io',
    subject: 'Vấn đề về thanh toán',
    content: 'Tôi đã thanh toán nhưng không nhận được gói VIP.',
    status: 'in-progress',
    createdAt: '2024-05-16 10:00:00',
    category: 'bug',
  },
  {
    id: 'fb13',
    userId: 'u4',
    userName: 'David Nguyen',
    userEmail: 'david.nguyen@tokki.io',
    subject: 'Cảm ơn về tính năng mới',
    content: 'Tính năng học offline rất tuyệt vời!',
    status: 'resolved',
    createdAt: '2024-05-15 16:30:00',
    category: 'other',
  },
  {
    id: 'fb14',
    userId: 'u5',
    userName: 'Emma Tran',
    userEmail: 'emma.tran@tokki.io',
    subject: 'Giao diện cần cải thiện',
    content: 'Màu sắc và font chữ cần được điều chỉnh để dễ đọc hơn.',
    status: 'new',
    createdAt: '2024-05-15 12:15:00',
    category: 'ui',
  },
  {
    id: 'fb15',
    userId: 'u9',
    userName: 'Ivy Chen',
    userEmail: 'ivy.chen@tokki.io',
    subject: 'Lỗi khi tải video',
    content: 'Video bài học không tải được khi kết nối mạng yếu.',
    status: 'in-progress',
    createdAt: '2024-05-14 14:45:00',
    category: 'bug',
  },
  {
    id: 'fb16',
    userId: 'u13',
    userName: 'Mia Johnson',
    userEmail: 'mia.johnson@tokki.io',
    subject: 'Đề xuất thêm chứng chỉ',
    content: 'Có thể cấp chứng chỉ sau khi hoàn thành khóa học không?',
    status: 'new',
    createdAt: '2024-05-14 09:20:00',
    category: 'feature',
  },
  {
    id: 'fb17',
    userId: 'u17',
    userName: 'Quinn Anderson',
    userEmail: 'quinn.anderson@tokki.io',
    subject: 'Vấn đề về thông báo',
    content: 'Thông báo không hiển thị đúng thời gian.',
    status: 'resolved',
    createdAt: '2024-05-13 15:30:00',
    category: 'bug',
  },
  {
    id: 'fb18',
    userId: 'u19',
    userName: 'Sam Thomas',
    userEmail: 'sam.thomas@tokki.io',
    subject: 'Góp ý về nội dung',
    content: 'Nội dung bài học rất hay và dễ hiểu.',
    status: 'closed',
    createdAt: '2024-05-13 11:00:00',
    category: 'other',
  },
  {
    id: 'fb19',
    userId: 'u20',
    userName: 'Tina Jackson',
    userEmail: 'tina.jackson@tokki.io',
    subject: 'Lỗi đăng ký',
    content: 'Không thể đăng ký tài khoản mới.',
    status: 'resolved',
    createdAt: '2024-05-12 13:45:00',
    category: 'bug',
  },
  {
    id: 'fb20',
    userId: 'u14',
    userName: 'Noah Davis',
    userEmail: 'noah.davis@tokki.io',
    subject: 'Đề xuất thêm tính năng chat',
    content: 'Có thể thêm tính năng chat với giáo viên không?',
    status: 'new',
    createdAt: '2024-05-12 10:30:00',
    category: 'feature',
  },
  {
    id: 'fb21',
    userId: 'u2',
    userName: 'Bob Staff',
    userEmail: 'bob@tokki.io',
    subject: 'Vấn đề về bảo mật',
    content: 'Cần cải thiện tính bảo mật của ứng dụng.',
    status: 'in-progress',
    createdAt: '2024-05-11 14:20:00',
    category: 'bug',
  },
  {
    id: 'fb22',
    userId: 'u3',
    userName: 'Carol User',
    userEmail: 'carol@tokki.io',
    subject: 'Cảm ơn về hỗ trợ',
    content: 'Đội ngũ hỗ trợ rất nhiệt tình và chuyên nghiệp.',
    status: 'closed',
    createdAt: '2024-05-11 09:15:00',
    category: 'other',
  },
]

// Mock data cho thanh toán
export const mockPayments = [
  {
    id: 'pay1',
    userId: 'u6',
    userName: 'Frank Lee',
    userEmail: 'frank.lee@tokki.io',
    packageId: 'p1',
    packageName: 'VIP MONTHLY',
    amount: 99000,
    status: 'completed',
    paymentMethod: 'credit_card',
    transactionId: 'TXN001234567',
    createdAt: '2024-05-21 10:30:00',
    completedAt: '2024-05-21 10:31:00',
  },
  {
    id: 'pay2',
    userId: 'u7',
    userName: 'Grace Kim',
    userEmail: 'grace.kim@tokki.io',
    packageId: 'p3',
    packageName: 'VIP ANNUAL',
    amount: 899000,
    status: 'pending',
    paymentMethod: 'bank_transfer',
    transactionId: 'TXN001234568',
    createdAt: '2024-05-21 09:15:00',
    completedAt: null,
  },
  {
    id: 'pay3',
    userId: 'u10',
    userName: 'Jack Wang',
    userEmail: 'jack.wang@tokki.io',
    packageId: 'p2',
    packageName: 'VIP SEMI-ANNUAL',
    amount: 499000,
    status: 'completed',
    paymentMethod: 'e_wallet',
    transactionId: 'TXN001234569',
    createdAt: '2024-05-20 14:20:00',
    completedAt: '2024-05-20 14:22:00',
  },
  {
    id: 'pay4',
    userId: 'u12',
    userName: 'Liam Brown',
    userEmail: 'liam.brown@tokki.io',
    packageId: 'p1',
    packageName: 'VIP MONTHLY',
    amount: 99000,
    status: 'failed',
    paymentMethod: 'credit_card',
    transactionId: 'TXN001234570',
    createdAt: '2024-05-20 11:45:00',
    completedAt: null,
  },
  {
    id: 'pay5',
    userId: 'u15',
    userName: 'Olivia Wilson',
    userEmail: 'olivia.wilson@tokki.io',
    packageId: 'p3',
    packageName: 'VIP ANNUAL',
    amount: 899000,
    status: 'completed',
    paymentMethod: 'credit_card',
    transactionId: 'TXN001234571',
    createdAt: '2024-05-19 16:30:00',
    completedAt: '2024-05-19 16:31:00',
  },
  {
    id: 'pay6',
    userId: 'u8',
    userName: 'Henry Park',
    userEmail: 'henry.park@tokki.io',
    packageId: 'p1',
    packageName: 'VIP MONTHLY',
    amount: 99000,
    status: 'completed',
    paymentMethod: 'e_wallet',
    transactionId: 'TXN001234572',
    createdAt: '2024-05-19 10:20:00',
    completedAt: '2024-05-19 10:21:00',
  },
  {
    id: 'pay7',
    userId: 'u11',
    userName: 'Kelly Zhang',
    userEmail: 'kelly.zhang@tokki.io',
    packageId: 'p2',
    packageName: 'VIP SEMI-ANNUAL',
    amount: 499000,
    status: 'pending',
    paymentMethod: 'bank_transfer',
    transactionId: 'TXN001234573',
    createdAt: '2024-05-18 14:15:00',
    completedAt: null,
  },
  {
    id: 'pay8',
    userId: 'u16',
    userName: 'Paul Martinez',
    userEmail: 'paul.martinez@tokki.io',
    packageId: 'p1',
    packageName: 'VIP MONTHLY',
    amount: 99000,
    status: 'completed',
    paymentMethod: 'credit_card',
    transactionId: 'TXN001234574',
    createdAt: '2024-05-18 09:30:00',
    completedAt: '2024-05-18 09:31:00',
  },
  {
    id: 'pay9',
    userId: 'u18',
    userName: 'Rachel Taylor',
    userEmail: 'rachel.taylor@tokki.io',
    packageId: 'p3',
    packageName: 'VIP ANNUAL',
    amount: 899000,
    status: 'completed',
    paymentMethod: 'credit_card',
    transactionId: 'TXN001234575',
    createdAt: '2024-05-17 15:45:00',
    completedAt: '2024-05-17 15:46:00',
  },
  {
    id: 'pay10',
    userId: 'u21',
    userName: 'Uma White',
    userEmail: 'uma.white@tokki.io',
    packageId: 'p1',
    packageName: 'VIP MONTHLY',
    amount: 99000,
    status: 'failed',
    paymentMethod: 'e_wallet',
    transactionId: 'TXN001234576',
    createdAt: '2024-05-17 11:20:00',
    completedAt: null,
  },
  {
    id: 'pay11',
    userId: 'u22',
    userName: 'Victor Harris',
    userEmail: 'victor.harris@tokki.io',
    packageId: 'p2',
    packageName: 'VIP SEMI-ANNUAL',
    amount: 499000,
    status: 'completed',
    paymentMethod: 'bank_transfer',
    transactionId: 'TXN001234577',
    createdAt: '2024-05-16 13:10:00',
    completedAt: '2024-05-16 13:12:00',
  },
  {
    id: 'pay12',
    userId: 'u4',
    userName: 'David Nguyen',
    userEmail: 'david.nguyen@tokki.io',
    packageId: 'p3',
    packageName: 'VIP ANNUAL',
    amount: 899000,
    status: 'completed',
    paymentMethod: 'credit_card',
    transactionId: 'TXN001234578',
    createdAt: '2024-05-16 10:00:00',
    completedAt: '2024-05-16 10:01:00',
  },
  {
    id: 'pay13',
    userId: 'u5',
    userName: 'Emma Tran',
    userEmail: 'emma.tran@tokki.io',
    packageId: 'p1',
    packageName: 'VIP MONTHLY',
    amount: 99000,
    status: 'pending',
    paymentMethod: 'e_wallet',
    transactionId: 'TXN001234579',
    createdAt: '2024-05-15 16:30:00',
    completedAt: null,
  },
  {
    id: 'pay14',
    userId: 'u9',
    userName: 'Ivy Chen',
    userEmail: 'ivy.chen@tokki.io',
    packageId: 'p2',
    packageName: 'VIP SEMI-ANNUAL',
    amount: 499000,
    status: 'completed',
    paymentMethod: 'credit_card',
    transactionId: 'TXN001234580',
    createdAt: '2024-05-15 12:15:00',
    completedAt: '2024-05-15 12:16:00',
  },
  {
    id: 'pay15',
    userId: 'u13',
    userName: 'Mia Johnson',
    userEmail: 'mia.johnson@tokki.io',
    packageId: 'p1',
    packageName: 'VIP MONTHLY',
    amount: 99000,
    status: 'completed',
    paymentMethod: 'e_wallet',
    transactionId: 'TXN001234581',
    createdAt: '2024-05-14 14:45:00',
    completedAt: '2024-05-14 14:46:00',
  },
  {
    id: 'pay16',
    userId: 'u17',
    userName: 'Quinn Anderson',
    userEmail: 'quinn.anderson@tokki.io',
    packageId: 'p3',
    packageName: 'VIP ANNUAL',
    amount: 899000,
    status: 'completed',
    paymentMethod: 'credit_card',
    transactionId: 'TXN001234582',
    createdAt: '2024-05-14 09:20:00',
    completedAt: '2024-05-14 09:21:00',
  },
  {
    id: 'pay17',
    userId: 'u19',
    userName: 'Sam Thomas',
    userEmail: 'sam.thomas@tokki.io',
    packageId: 'p2',
    packageName: 'VIP SEMI-ANNUAL',
    amount: 499000,
    status: 'failed',
    paymentMethod: 'bank_transfer',
    transactionId: 'TXN001234583',
    createdAt: '2024-05-13 15:30:00',
    completedAt: null,
  },
  {
    id: 'pay18',
    userId: 'u20',
    userName: 'Tina Jackson',
    userEmail: 'tina.jackson@tokki.io',
    packageId: 'p1',
    packageName: 'VIP MONTHLY',
    amount: 99000,
    status: 'completed',
    paymentMethod: 'credit_card',
    transactionId: 'TXN001234584',
    createdAt: '2024-05-13 11:00:00',
    completedAt: '2024-05-13 11:01:00',
  },
  {
    id: 'pay19',
    userId: 'u14',
    userName: 'Noah Davis',
    userEmail: 'noah.davis@tokki.io',
    packageId: 'p3',
    packageName: 'VIP ANNUAL',
    amount: 899000,
    status: 'pending',
    paymentMethod: 'e_wallet',
    transactionId: 'TXN001234585',
    createdAt: '2024-05-12 13:45:00',
    completedAt: null,
  },
  {
    id: 'pay20',
    userId: 'u2',
    userName: 'Bob Staff',
    userEmail: 'bob@tokki.io',
    packageId: 'p1',
    packageName: 'VIP MONTHLY',
    amount: 99000,
    status: 'completed',
    paymentMethod: 'credit_card',
    transactionId: 'TXN001234586',
    createdAt: '2024-05-12 10:30:00',
    completedAt: '2024-05-12 10:31:00',
  },
  {
    id: 'pay21',
    userId: 'u3',
    userName: 'Carol User',
    userEmail: 'carol@tokki.io',
    packageId: 'p2',
    packageName: 'VIP SEMI-ANNUAL',
    amount: 499000,
    status: 'completed',
    paymentMethod: 'bank_transfer',
    transactionId: 'TXN001234587',
    createdAt: '2024-05-11 14:20:00',
    completedAt: '2024-05-11 14:22:00',
  },
  {
    id: 'pay22',
    userId: 'u1',
    userName: 'Alice Admin',
    userEmail: 'alice@tokki.io',
    packageId: 'p3',
    packageName: 'VIP ANNUAL',
    amount: 899000,
    status: 'cancelled',
    paymentMethod: 'credit_card',
    transactionId: 'TXN001234588',
    createdAt: '2024-05-11 09:15:00',
    completedAt: null,
  },
]

// Mock data cho báo cáo doanh thu
export const mockRevenueData = [
  { month: 'Tháng 1', revenue: 4500000, subscriptions: 45 },
  { month: 'Tháng 2', revenue: 5200000, subscriptions: 52 },
  { month: 'Tháng 3', revenue: 4800000, subscriptions: 48 },
  { month: 'Tháng 4', revenue: 6100000, subscriptions: 61 },
  { month: 'Tháng 5', revenue: 5800000, subscriptions: 58 },
  { month: 'Tháng 6', revenue: 7200000, subscriptions: 72 },
]

export const mockPackageRevenueData = [
  { package: 'VIP MONTHLY', revenue: 3200000, count: 32 },
  { package: 'VIP SEMI-ANNUAL', revenue: 1800000, count: 3 },
  { package: 'VIP ANNUAL', revenue: 2200000, count: 2 },
]

// Mock data cho email templates
export const mockEmailTemplates = [
  { id: 'welcome', name: 'Email chào mừng', description: 'Gửi khi người dùng đăng ký mới' },
  { id: 'reminder', name: 'Email nhắc nhở', description: 'Nhắc nhở người dùng học bài' },
  { id: 'achievement', name: 'Email thành tích', description: 'Chúc mừng khi đạt thành tích' },
  { id: 'promotion', name: 'Email khuyến mãi', description: 'Thông báo chương trình khuyến mãi' },
]

// Constants cho các screens
export const feedbackStatusColors = {
  new: 'blue',
  'in-progress': 'orange',
  resolved: 'green',
  closed: 'default',
}

export const feedbackCategoryLabels = {
  ui: 'Giao diện',
  bug: 'Lỗi',
  feature: 'Tính năng',
  other: 'Khác',
}

export const paymentStatusColors = {
  completed: 'green',
  pending: 'orange',
  failed: 'red',
  cancelled: 'default',
}

export const paymentMethodLabels = {
  credit_card: 'Thẻ tín dụng',
  bank_transfer: 'Chuyển khoản',
  e_wallet: 'Ví điện tử',
}

// Mock data cho Báo cáo thống kê dữ liệu A.I
export const mockAIStatistics = {
  overview: {
    totalQueries: 125430,
    totalUsers: 3420,
    averageResponseTime: 1.2,
    accuracyRate: 94.5,
    totalTokensUsed: 2450000,
  },
  usageByFeature: [
    { feature: 'Dịch thuật', count: 45230, percentage: 36.1 },
    { feature: 'Giải thích ngữ pháp', count: 38120, percentage: 30.4 },
    { feature: 'Tạo bài tập', count: 22450, percentage: 17.9 },
    { feature: 'Chấm điểm phát âm', count: 12890, percentage: 10.3 },
    { feature: 'Tư vấn học tập', count: 6740, percentage: 5.4 },
  ],
  usageByDay: [
    { date: '2024-05-01', queries: 3420, users: 890 },
    { date: '2024-05-02', queries: 3850, users: 920 },
    { date: '2024-05-03', queries: 4120, users: 950 },
    { date: '2024-05-04', queries: 3980, users: 910 },
    { date: '2024-05-05', queries: 4250, users: 980 },
    { date: '2024-05-06', queries: 4680, users: 1020 },
    { date: '2024-05-07', queries: 4520, users: 990 },
    { date: '2024-05-08', queries: 4390, users: 970 },
    { date: '2024-05-09', queries: 4560, users: 1000 },
    { date: '2024-05-10', queries: 4720, users: 1030 },
    { date: '2024-05-11', queries: 4890, users: 1050 },
    { date: '2024-05-12', queries: 5010, users: 1080 },
  ],
  accuracyByFeature: [
    { feature: 'Dịch thuật', accuracy: 96.8, totalQueries: 45230 },
    { feature: 'Giải thích ngữ pháp', accuracy: 95.2, totalQueries: 38120 },
    { feature: 'Tạo bài tập', accuracy: 93.5, totalQueries: 22450 },
    { feature: 'Chấm điểm phát âm', accuracy: 91.8, totalQueries: 12890 },
    { feature: 'Tư vấn học tập', accuracy: 89.4, totalQueries: 6740 },
  ],
  topUsers: [
    { userId: 'u1', userName: 'Alice Admin', queries: 1250, lastUsed: '2024-05-12 14:30' },
    { userId: 'u6', userName: 'Frank Lee', queries: 980, lastUsed: '2024-05-12 13:15' },
    { userId: 'u10', userName: 'Jack Wang', queries: 850, lastUsed: '2024-05-12 12:45' },
    { userId: 'u12', userName: 'Liam Brown', queries: 720, lastUsed: '2024-05-12 11:20' },
    { userId: 'u16', userName: 'Paul Martinez', queries: 680, lastUsed: '2024-05-12 10:10' },
  ],
  costAnalysis: [
    { month: 'Tháng 1', tokens: 1800000, cost: 5400000, queries: 98500 },
    { month: 'Tháng 2', tokens: 1950000, cost: 5850000, queries: 102300 },
    { month: 'Tháng 3', tokens: 2100000, cost: 6300000, queries: 108900 },
    { month: 'Tháng 4', tokens: 2280000, cost: 6840000, queries: 115600 },
    { month: 'Tháng 5', tokens: 2450000, cost: 7350000, queries: 125430 },
  ],
}

