export const KOREA_TRIVIA = [
  { topic: 'Pali-pali', content: 'Triết lý "Nhanh lên" thúc đẩy mọi dịch vụ từ giao hàng đến xây dựng thần tốc.' },
  { topic: 'Internet', content: 'Tốc độ mạng thuộc hàng nhanh nhất thế giới và Wi-Fi miễn phí phủ sóng khắp nơi.' },
  { topic: 'Giao hàng', content: 'Bạn có thể đặt đồ ăn ra công viên hay bờ sông mà không cần địa chỉ số nhà cụ thể.' },
  { topic: 'CH Tiện lợi', content: 'Hoạt động 24/7, là nơi nấu mì tự động, sạc pin và thậm chí là gửi bưu phẩm.' },
  { topic: 'Tàu điện ngầm', content: 'Ghế ngồi có sưởi ấm vào mùa đông và điều hòa mát rượi vào mùa hè.' },
  { topic: 'Thẻ T-Money', content: 'Một chiếc thẻ dùng cho mọi phương tiện công cộng và thanh toán được ở cửa hàng.' },
  { topic: 'PC Bang', content: 'Tiệm nét cao cấp mở 24/24, phục vụ đồ ăn tại chỗ, cấu hình máy cực khủng.' },
  { topic: 'An ninh', content: 'Cực kỳ an toàn, có thể để điện thoại/ví trên bàn quán cafe mà không sợ mất.' },
  { topic: 'Shop tự động', content: 'Nhiều cửa hàng không người bán (kem, văn phòng phẩm), khách tự giác thanh toán.' },
  { topic: 'Noraebang', content: 'Văn hóa hát Karaoke giải tỏa stress sau giờ làm việc là một phần tất yếu.' },
  { topic: 'Ondol', content: 'Hệ thống sưởi dưới sàn nhà truyền thống giúp giữ ấm đôi chân suốt mùa đông.' },
  { topic: 'Phân loại rác', content: 'Quy định cực nghiêm: rác thực phẩm, rác tái chế và rác thường phải tách riêng.' },
  { topic: 'Taxi đen', content: 'Là loại taxi cao cấp, tài xế kinh nghiệm, dịch vụ tốt hơn và giá cước cũng đắt hơn.' },
  { topic: 'Số 4 xui xẻo', content: 'Số 4 được coi là điềm xấu (âm Hán gần chữ "Tử"), thang máy thường ghi chữ "F".' },
  { topic: 'Chợ đêm', content: 'Các khu như Dongdaemun hoạt động nhộn nhịp nhất từ 11h đêm đến sáng sớm.' },
  { topic: 'QR Code', content: 'Dùng cho mọi thứ: từ xem menu, thanh toán đến tra cứu thông tin xe bus.' },
  { topic: 'Thành phố thông minh', content: 'Khu đô thị Songdo có hệ thống xử lý rác bằng đường ống ngầm trực tiếp từ nhà.' },
  { topic: 'App Kakao', content: 'KakaoTalk là "siêu ứng dụng" để nhắn tin, gọi taxi, tặng quà và thanh toán.' },
  { topic: 'Bus thông minh', content: 'Điểm dừng có bảng điện tử báo chính xác số phút xe đến và có ổ cắm sạc.' },
  { topic: 'Khóa số', content: 'Hầu hết nhà ở Hàn dùng khóa mã số hoặc vân tay thay vì chìa khóa cơ truyền thống.' },
  { topic: 'Y tế', content: 'Hệ thống bảo hiểm và dịch vụ y tế cực kỳ hiện đại, nhanh chóng và chuyên nghiệp.' },
  { topic: 'Webtoon', content: 'Hàn Quốc dẫn đầu thế giới về định dạng truyện tranh đọc dọc trên điện thoại.' },
  { topic: 'Robot phục vụ', content: 'Robot bưng bê đồ ăn đang trở nên phổ biến tại các nhà hàng hiện đại.' },
  { topic: 'Mỹ phẩm nam', content: 'Nam giới Hàn Quốc rất chú trọng chăm sóc da và tiêu thụ mỹ phẩm hàng đầu thế giới.' },
  { topic: 'Pojangmacha', content: 'Những lều bạt màu cam vỉa hè là địa điểm nhậu đêm kinh điển trong phim ảnh.' },
  { topic: 'Tuổi Hàn', content: 'Sinh ra đã tính là 1 tuổi và tất cả mọi người cùng tăng thêm 1 tuổi vào ngày Tết.' },
  { topic: 'Kính ngữ', content: 'Ngôn ngữ thay đổi hoàn toàn tùy theo tuổi tác và địa vị người đối diện.' },
  { topic: 'Nunchi', content: 'Nghệ thuật "nhìn sắc mặt" để ứng xử khéo léo mà không cần đối phương nói ra.' },
  { topic: 'MBTI', content: 'Bài kiểm tra tính cách trở thành chủ đề bắt chuyện "quốc dân" để tìm hiểu nhau.' },
  { topic: 'Nhóm máu', content: 'Nhiều người vẫn tin nhóm máu quyết định tính cách và độ hợp nhau trong tình yêu.' },
  { topic: 'Quà tân gia', content: 'Thường tặng giấy vệ sinh (mong mọi việc suôn sẻ) hoặc bột giặt (mong sự giàu có).' },
  { topic: 'Hoesik', content: 'Những bữa tiệc công ty là dịp để gắn kết đồng nghiệp nhưng cũng đầy áp lực.' },
  { topic: 'Lễ cưới nhanh', content: 'Đám cưới thường diễn ra gọn lẹ trong 1 tiếng tại các trung tâm tiệc cưới chuyên dụng.' },
  { topic: 'Tang lễ', content: 'Gia đình người mất thường phục vụ đồ ăn (thường là súp thịt bò) cho khách viếng.' },
  { topic: 'Quà tốt nghiệp', content: 'Phẫu thuật thẩm mỹ là món quà phổ biến cha mẹ tặng con để tự tin tìm việc.' },
  { topic: 'Đồ đôi', content: 'Các cặp đôi thích mặc áo, giày hoặc đội mũ giống hệt nhau để thể hiện tình cảm.' },
  { topic: 'Ngày 14 hàng tháng', content: 'Không chỉ có 14/2, mỗi tháng đều có một ngày lễ tình nhân với ý nghĩa khác nhau.' },
  { topic: 'Họ phổ biến', content: 'Gần một nửa dân số Hàn Quốc mang họ Kim, Lee hoặc Park.' },
  { topic: 'Ưu tiên người già', content: 'Ghế dành cho người già trên tàu luôn được bỏ trống dù tàu có đông đến đâu.' },
  { topic: 'Che miệng khi cười', content: 'Một nét văn hóa giữ kẽ, lịch sự của phụ nữ Hàn khi cười lớn hoặc ăn uống.' },
  { topic: 'Dùng hai tay', content: 'Luôn đưa và nhận đồ vật (đặc biệt là rượu) bằng hai tay để tỏ lòng kính trọng.' },
  { topic: 'Goshiwon', content: 'Những phòng trọ siêu nhỏ, chỉ vừa chỗ ngủ cho sinh viên hoặc người đi làm nghèo.' },
  { topic: 'Hanja', content: 'Chữ Hán vẫn được dạy trong trường học để giúp hiểu sâu nghĩa các từ vựng khó.' },
  { topic: 'Cờ Thái cực', content: 'Mang ý nghĩa triết học về sự cân bằng vũ trụ thông qua âm dương (đỏ-xanh).' },
  { topic: 'Mặc Hanbok', content: 'Thuê Hanbok đi tham quan sẽ giúp bạn được miễn phí vé vào các cung điện cổ.' },
  { topic: 'Tết Chuseok', content: 'Lễ tạ ơn của người Hàn, dịp quan trọng nhất để về quê đoàn tụ và cúng tổ tiên.' },
  { topic: 'Tết Seollal', content: 'Tết Nguyên Đán, trẻ em lạy người lớn (Sebae) và nhận tiền mừng tuổi.' },
  { topic: 'Làng Hanok', content: 'Những khu nhà cổ nằm ngay giữa lòng thủ đô Seoul hiện đại (như Bukchon).' },
  { topic: 'Leo núi', content: 'Hoạt động yêu thích nhất của người trung niên Hàn Quốc vào mỗi cuối tuần.' },
  { topic: 'Hagwon', content: 'Các lò luyện thi hoạt động đến tận đêm khuya do áp lực học hành cực lớn.' },
  { topic: 'Tủ lạnh Kimchi', content: 'Mỗi gia đình thường có một tủ lạnh riêng biệt để bảo quản các loại Kimchi khác nhau.' },
  { topic: 'Banchan miễn phí', content: 'Các món phụ được phục vụ thoải mái và bạn có thể xin thêm mà không mất tiền.' },
  { topic: 'Bibimbap', content: 'Món cơm trộn cân bằng dinh dưỡng, ban đầu là món ăn dành cho tầng lớp quý tộc.' },
  { topic: 'Samgyeopsal', content: 'Thịt ba chỉ nướng phải cuốn cùng lá nhíp, tỏi và tương trộn mới đúng điệu.' },
  { topic: 'Rượu Soju', content: 'Thức uống quốc dân, rẻ tiền và có mặt trong mọi cuộc vui của người Hàn.' },
  { topic: 'Makgeolli', content: 'Rượu gạo đục truyền thống, thường được uống khi trời mưa kèm với bánh xèo.' },
  { topic: 'Naengmyeon', content: 'Mì lạnh có nước dùng đóng băng sền sệt, sợi mì dai, cực kỳ bắt miệng mùa hè.' },
  { topic: 'Vua Gà rán', content: 'Số lượng quán gà rán ở Hàn nhiều hơn cả tổng số cửa hàng McDonald\'s toàn cầu.' },
  { topic: 'Súp rong biển', content: 'Món ăn bắt buộc trong ngày sinh nhật để tỏ lòng biết ơn sự hy sinh của mẹ.' },
  { topic: 'Ăn cay giải stress', content: 'Người Hàn tin rằng đồ ăn cay nóng giúp vã mồ hôi và giảm bớt căng thẳng tâm lý.' },
  { topic: 'Tiêu thụ mì gói', content: 'Hàn Quốc luôn nằm trong top các nước ăn nhiều mì tôm nhất thế giới.' },
  { topic: 'Street food', content: 'Bánh gạo cay (Tteokbokki) và chả cá (Odeng) là combo ăn vặt kinh điển.' },
  { topic: 'Gimbap', content: 'Cơm cuộn là lựa chọn hàng đầu cho các chuyến dã ngoại vì tính tiện dụng.' },
  { topic: 'Trứng Jjimjilbang', content: 'Trứng được nướng trong phòng xông hơi có vỏ nâu, lòng trắng dai và rất thơm.' },
  { topic: 'Cafe gói 3in1', content: 'Loại cafe hòa tan trong gói dài là "máu" của dân văn phòng Hàn Quốc.' },
  { topic: 'Chợ Noryangjin', content: 'Nơi bạn mua hải sản tươi sống và mang lên tầng trên nhờ nhà hàng nấu ngay.' },
  { topic: 'Jajangmyeon', content: 'Mì tương đen là món ăn phổ biến cho người độc thân vào ngày "Black Day" (14/4).' },
  { topic: 'Trà sức khỏe', content: 'Thay vì trà mạn, người Hàn thích trà táo đỏ, trà gừng, trà mộc qua để giữ ấm.' },
  { topic: 'Nhân sâm', content: 'Hàn Quốc là quốc gia xuất khẩu nhân sâm chất lượng cao nhất thế giới.' },
  { topic: 'Nurungji', content: 'Cơm cháy nấu với nước dùng làm thức uống tráng miệng thơm bùi sau bữa ăn.' },
  { topic: 'Gimjang', content: 'Văn hóa muối Kimchi tập thể của các gia đình trước khi mùa đông tới.' },
  { topic: 'Đũa kim loại', content: 'Người Hàn dùng đũa dẹt bằng sắt thay vì gỗ để sạch sẽ và bền hơn.' },
  { topic: 'Nước lọc free', content: 'Gần như 100% quán ăn tại Hàn đều cung cấp nước lọc đá miễn phí cho khách.' },
  { topic: 'Nước tự phục vụ', content: 'Biểu hiệu "물은 셀프" (Nước tự phục vụ) rất phổ biến trong các nhà hàng bình dân.' },
  { topic: 'Mukbang', content: 'Xu hướng quay video ăn uống cực lớn phát nguồn từ Hàn Quốc và gây sốt toàn cầu.' },
  { topic: 'Hallyu', content: 'Làn sóng văn hóa (K-Pop, phim ảnh) lan tỏa mạnh mẽ ra khắp thế giới.' },
  { topic: 'Lightstick', content: 'Mỗi nhóm nhạc K-Pop có một biểu tượng đèn riêng để fan cổ vũ trong concert.' },
  { topic: 'Đảo Nami', content: 'Hòn đảo xinh đẹp nổi tiếng toàn cầu nhờ bộ phim "Bản tình ca mùa đông".' },
  { topic: 'Tháp Namsan', content: 'Nơi biểu tượng cho tình yêu vĩnh cửu với hàng triệu ổ khóa đầy màu sắc.' },
  { topic: 'Đảo Jeju', content: 'Hòn đảo thiên đường của đá núi lửa, gió và đặc sản quýt ngọt.' },
  { topic: 'Haenyeo', content: 'Những "nàng tiên cá" đời thực ở Jeju lặn biển không cần bình dưỡng khí.' },
  { topic: 'Thành phố Busan', content: 'Thành phố cảng lớn nhất, nổi tiếng with các bãi biển và liên hoan phim quốc tế.' },
  { topic: 'Làng Gamcheon', content: 'Ngôi làng bích họa rực rỡ tại Busan, điểm check-in không thể bỏ qua.' },
  { topic: 'Khu DMZ', content: 'Biên giới Nam-Bắc Triều Tiên, điểm du lịch quân sự đặc biệt nhất thế giới.' },
  { topic: 'Suối Cheonggyecheon', content: 'Dự án cải tạo đô thị vĩ đại, biến con kênh rác thành dòng suối mát giữa Seoul.' },
  { topic: 'Everland', content: 'Công viên giải trí lớn nhất Hàn Quốc with tàu lượn bằng gỗ cực kỳ đáng sợ.' },
  { topic: 'Lotte World', content: 'Công viên giải trí trong nhà lớn nhất thế giới, nằm ngay giữa trung tâm thành phố.' },
  { topic: 'Cung Gyeongbok', content: 'Cung điện lớn nhất trong 5 cung điện ở Seoul, nơi diễn ra lễ đổi gác mỗi ngày.' },
  { topic: 'Itaewon', content: 'Khu phố "Tây" nhất Hàn Quốc with cộng đồng người nước ngoài đông đúc.' },
  { topic: 'Busking ở Hongdae', content: 'Các buổi biểu diễn âm nhạc/nhảy múa đường phố diễn ra hàng đêm tại Hongdae.' },
  { topic: 'Gangnam', content: 'Khu phố sầm uất dành cho giới thượng lưu, biểu tượng của sự sang trọng.' },
  { topic: 'Hoa anh đào', content: 'Đầu tháng 4 cả nước Hàn nhuộm trong sắc hồng trắng của hoa anh đào rực rỡ.' },
  { topic: 'Lá đỏ mùa thu', content: 'Cảnh sắc rừng núi chuyển màu vàng đỏ vào tháng 10 đẹp như tranh vẽ.' },
  { topic: 'E-sports', content: 'Game thủ chuyên nghiệp (như Faker) được coi là những ngôi sao và anh hùng quốc gia.' },
  { topic: 'Lễ hội bùn', content: 'Lễ hội Boryeong thu hút hàng triệu khách quốc tế đến chơi bùn vào mùa hè.' },
  { topic: 'Sân bay Incheon', content: 'Luôn đứng top sân bay tốt nhất thế giới with đủ loại dịch vụ thư giãn, mua sắm.' },
  { topic: 'Kakao Friends', content: 'Các linh vật như gấu Ryan hay thỏ Muzi có cửa hàng lưu niệm cực lớn.' },
  { topic: 'K-Beauty', content: 'Olive Young là chuỗi cửa hàng mỹ phẩm mà bất cứ ai đến Hàn cũng phải ghé qua.' },
  { topic: 'Ngủ tại Jjimjilbang', content: 'Bạn có thể ngủ qua đêm tại các phòng xông hơi with giá cực rẻ (khoảng 15k-20k Won).' },
  { topic: 'Cầu sông Hàn', content: 'Có 31 cây cầu with đèn LED lung linh, mỗi tối thường có nhạc nước ở cầu Banpo.' },
]
